# Generated by Django 6.0.7 on 2026-08-07 10:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("surveillance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportCNVZ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre du rapport"),
                ),
                (
                    "date_debut_semaine",
                    models.DateField(verbose_name="Date de début de la semaine ISO"),
                ),
                (
                    "date_fin_semaine",
                    models.DateField(verbose_name="Date de fin de la semaine ISO"),
                ),
                (
                    "semaine_iso",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="Numéro de semaine ISO"
                    ),
                ),
                (
                    "annee_iso",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="Année ISO"
                    ),
                ),
                (
                    "fichier_rapport",
                    models.FileField(
                        upload_to="rapports_cnvz/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "ppt", "pptx"]
                            )
                        ],
                        verbose_name="Rapport CNVZ ",
                    ),
                ),
                (
                    "depose_le",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et heure du dépôt"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "depose_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapports_cnvz_deposes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Déposé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport CNVZ",
                "verbose_name_plural": "Rapports CNVZ",
                "ordering": ["-annee_iso", "-semaine_iso"],
            },
        ),
        migrations.CreateModel(
            name="RapportGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut_semaine",
                    models.DateField(verbose_name="Date de début de la semaine ISO"),
                ),
                (
                    "date_fin_semaine",
                    models.DateField(verbose_name="Date de fin de la semaine ISO"),
                ),
                (
                    "semaine_iso",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="Numéro de semaine ISO"
                    ),
                ),
                (
                    "annee_iso",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="Année ISO"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("genere", "Généré")],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "date_generation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapports_globaux_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "formulaires",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rapports_globaux",
                        to="surveillance.formulaire",
                        verbose_name="Formulaires humains consolidés",
                    ),
                ),
                (
                    "rapport_cnvz",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapport_global",
                        to="reports.rapportcnvz",
                        verbose_name="Rapport CNVZ associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport global",
                "verbose_name_plural": "Rapports globaux",
                "ordering": ["-annee_iso", "-semaine_iso"],
            },
        ),
        migrations.CreateModel(
            name="ConclusionGlobale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField(verbose_name="Conclusion globale")),
                (
                    "creee_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "modifiee_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifiée le"),
                ),
                (
                    "redigee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conclusions_globales_redigees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rédigée par",
                    ),
                ),
                (
                    "rapport_global",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conclusion_globale",
                        to="reports.rapportglobal",
                        verbose_name="Rapport global",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conclusion globale",
                "verbose_name_plural": "Conclusions globales",
            },
        ),
        migrations.AddConstraint(
            model_name="rapportcnvz",
            constraint=models.UniqueConstraint(
                fields=("annee_iso", "semaine_iso"),
                name="rapport_cnvz_unique_par_semaine",
            ),
        ),
        migrations.AddConstraint(
            model_name="rapportglobal",
            constraint=models.UniqueConstraint(
                fields=("annee_iso", "semaine_iso"),
                name="rapport_global_unique_par_semaine",
            ),
        ),
    ]
