# Generated by Django 6.0.7 on 2026-07-25 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaireCentral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rapport", models.DateField()),
                ("semaine_iso", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("soumis", "Soumis")],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "rapport_global",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="formulaires_central",
                        to="reports.rapportglobal",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        related_name="formulaires_centraux", to="regions.region"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaireRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rapport", models.DateField()),
                ("semaine_iso", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("soumis", "Soumis")],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "rapport_global",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="formulaires_region",
                        to="reports.rapportglobal",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formulaires",
                        to="regions.region",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_evenement", models.CharField(max_length=100)),
                ("statut", models.CharField(max_length=20)),
                (
                    "formulaire_central",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="surveillance.formulairecentral",
                    ),
                ),
                (
                    "formulaire_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="surveillance.formulaireregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConclusionRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                (
                    "formulaire_region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conclusion",
                        to="surveillance.formulaireregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaladieDeclaree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_maladie", models.CharField(max_length=100)),
                ("nb_cas", models.PositiveIntegerField(default=0)),
                ("nb_deces", models.PositiveIntegerField(default=0)),
                ("nb_hospitalises", models.PositiveIntegerField(default=0)),
                (
                    "formulaire_central",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maladies",
                        to="surveillance.formulairecentral",
                    ),
                ),
                (
                    "formulaire_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maladies",
                        to="surveillance.formulaireregion",
                    ),
                ),
            ],
        ),
    ]
