# Generated by Django 6.0.7 on 2026-07-30 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportCentral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semaine_iso", models.PositiveIntegerField()),
                ("annee", models.PositiveIntegerField()),
                ("fichier", models.FileField(upload_to="rapports_centraux/")),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportHebdomadaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rapport", models.DateField()),
                ("semaine_iso", models.PositiveIntegerField()),
                ("annee", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("soumis", "Soumis")],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("conclusion", models.TextField(blank=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to="regions.region",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaladieDeclaree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_maladie", models.CharField(max_length=100)),
                ("nb_cas", models.PositiveIntegerField(default=0)),
                ("nb_deces", models.PositiveIntegerField(default=0)),
                ("nb_hospitalises", models.PositiveIntegerField(default=0)),
                (
                    "rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maladies",
                        to="surveillance.rapporthebdomadaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_evenement", models.CharField(max_length=100)),
                ("statut", models.CharField(max_length=20)),
                (
                    "rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="surveillance.rapporthebdomadaire",
                    ),
                ),
            ],
        ),
    ]
