# Generated by Django 6.0.7 on 2026-08-07 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclarationWNV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut_enquete",
                    models.CharField(
                        choices=[
                            ("non", "Non"),
                            ("en_cours", "En cours"),
                            ("oui", "Oui"),
                        ],
                        default="non",
                        max_length=20,
                        verbose_name="Enquête autour des cas",
                    ),
                ),
                (
                    "date_enquete",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de l'enquête"
                    ),
                ),
                (
                    "statut_riposte",
                    models.CharField(
                        choices=[
                            ("non", "Non"),
                            ("en_cours", "En cours"),
                            ("oui", "Oui"),
                        ],
                        default="non",
                        max_length=20,
                        verbose_name="Riposte",
                    ),
                ),
                (
                    "date_riposte",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de la riposte"
                    ),
                ),
                (
                    "mesures_riposte",
                    models.TextField(blank=True, verbose_name="Mesures de riposte"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Maladie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nom de la maladie"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Disponible dans la liste"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasWNV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("suspect", "Suspect"),
                            ("probable", "Probable"),
                            ("confirme", "Confirmé"),
                        ],
                        max_length=20,
                        verbose_name="Classification du cas",
                    ),
                ),
                ("decede", models.BooleanField(default=False, verbose_name="Décédé")),
                (
                    "date_deces",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du décès"
                    ),
                ),
                (
                    "declaration_wnv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cas",
                        to="surveillance.declarationwnv",
                        verbose_name="Déclaration WNV",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formulaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_debut_semaine",
                    models.DateField(verbose_name="Date de début de la semaine ISO"),
                ),
                (
                    "date_fin_semaine",
                    models.DateField(verbose_name="Date de fin de la semaine ISO"),
                ),
                (
                    "date_saisie",
                    models.DateField(verbose_name="Date de saisie et de soumission"),
                ),
                (
                    "semaine_iso",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="Numéro de semaine ISO"
                    ),
                ),
                (
                    "annee_iso",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="Année ISO"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("soumis", "Soumis")],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formulaires",
                        to="regions.region",
                        verbose_name="Région concernée",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formulaires",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur ayant saisi le formulaire",
                    ),
                ),
            ],
            options={
                "ordering": ["-annee_iso", "-semaine_iso", "-date_saisie"],
            },
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant_evenement",
                    models.CharField(
                        max_length=50, verbose_name="Identifiant de l'évènement"
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("biologique", "Biologique"),
                            ("chimique", "Chimique"),
                            ("radiologique", "Radiologique"),
                            ("nucleaire", "Nucléaire"),
                        ],
                        max_length=20,
                        verbose_name="Type d'évènement",
                    ),
                ),
                (
                    "nature_evenement",
                    models.CharField(
                        max_length=250, verbose_name="Nature de l'évènement"
                    ),
                ),
                (
                    "autre_nature",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Autre nature à préciser",
                    ),
                ),
                ("date_occurrence", models.DateField(verbose_name="Date d'occurrence")),
                (
                    "lieu_occurrence",
                    models.CharField(max_length=200, verbose_name="Lieu d'occurrence"),
                ),
                ("date_detection", models.DateField(verbose_name="Date de détection")),
                (
                    "source_detection",
                    models.CharField(
                        max_length=250, verbose_name="Source de détection"
                    ),
                ),
                (
                    "autre_source_detection",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Autre source de détection",
                    ),
                ),
                (
                    "date_confirmation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de confirmation"
                    ),
                ),
                (
                    "source_verification",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Source de vérification",
                    ),
                ),
                (
                    "niveau_risque",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("modere", "Modéré"),
                            ("eleve", "Élevé"),
                        ],
                        max_length=20,
                        verbose_name="Évaluation rapide du risque",
                    ),
                ),
                (
                    "mesures_riposte",
                    models.TextField(blank=True, verbose_name="Mesures de riposte"),
                ),
                (
                    "date_debut_riposte",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de début de la riposte",
                    ),
                ),
                (
                    "date_fin_riposte",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin de la riposte"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_cours", "En cours"), ("cloture", "Clôturé")],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut de l'évènement",
                    ),
                ),
                (
                    "difficultes",
                    models.TextField(
                        blank=True,
                        verbose_name="Difficultés d'investigation et de riposte",
                    ),
                ),
                (
                    "formulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="surveillance.formulaire",
                        verbose_name="Formulaire",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="declarationwnv",
            name="formulaire",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="declaration_wnv",
                to="surveillance.formulaire",
                verbose_name="Formulaire",
            ),
        ),
        migrations.CreateModel(
            name="ConclusionIndicateurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conclusions",
                    models.TextField(
                        blank=True, verbose_name="Principales conclusions"
                    ),
                ),
                (
                    "difficultes",
                    models.TextField(blank=True, verbose_name="Difficultés"),
                ),
                (
                    "recommandations",
                    models.TextField(blank=True, verbose_name="Recommandations"),
                ),
                (
                    "formulaire",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conclusion_indicateurs",
                        to="surveillance.formulaire",
                        verbose_name="Formulaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConclusionEvenements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conclusions",
                    models.TextField(
                        blank=True, verbose_name="Principales conclusions"
                    ),
                ),
                (
                    "difficultes",
                    models.TextField(blank=True, verbose_name="Difficultés"),
                ),
                (
                    "recommandations",
                    models.TextField(blank=True, verbose_name="Recommandations"),
                ),
                (
                    "formulaire",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conclusion_evenements",
                        to="surveillance.formulaire",
                        verbose_name="Formulaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasMAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Âge")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("feminin", "Féminin"),
                            ("masculin", "Masculin"),
                            ("autre", "Autre / non précisé"),
                        ],
                        max_length=20,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "type_vaccin",
                    models.CharField(
                        max_length=200, verbose_name="Type de vaccin administré"
                    ),
                ),
                (
                    "date_administration_vaccin",
                    models.DateField(verbose_name="Date d'administration du vaccin"),
                ),
                (
                    "date_apparition_symptomes",
                    models.DateField(verbose_name="Date d'apparition des symptômes"),
                ),
                ("type_symptomes", models.TextField(verbose_name="Type de symptômes")),
                (
                    "hospitalise",
                    models.BooleanField(default=False, verbose_name="Hospitalisé"),
                ),
                (
                    "date_hospitalisation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'hospitalisation"
                    ),
                ),
                (
                    "evolution",
                    models.CharField(
                        choices=[
                            ("guerison", "Guérison"),
                            ("deces", "Décès"),
                            ("en_cours", "Évolution en cours"),
                        ],
                        max_length=20,
                        verbose_name="Évolution",
                    ),
                ),
                (
                    "formulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cas_mapi",
                        to="surveillance.formulaire",
                        verbose_name="Formulaire",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormulaireMaladie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut_enquete",
                    models.CharField(
                        choices=[
                            ("non", "Non"),
                            ("en_cours", "En cours"),
                            ("oui", "Oui"),
                        ],
                        default="non",
                        max_length=20,
                        verbose_name="Enquête autour des cas",
                    ),
                ),
                (
                    "date_enquete",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de l'enquête"
                    ),
                ),
                (
                    "statut_riposte",
                    models.CharField(
                        choices=[
                            ("non", "Non"),
                            ("en_cours", "En cours"),
                            ("oui", "Oui"),
                        ],
                        default="non",
                        max_length=20,
                        verbose_name="Riposte",
                    ),
                ),
                (
                    "date_riposte",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de la riposte"
                    ),
                ),
                (
                    "mesures_riposte",
                    models.TextField(blank=True, verbose_name="Mesures de riposte"),
                ),
                (
                    "formulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maladies_declarees",
                        to="surveillance.formulaire",
                        verbose_name="Formulaire",
                    ),
                ),
                (
                    "maladie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declarations",
                        to="surveillance.maladie",
                        verbose_name="Maladie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CasMaladie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_cas",
                    models.CharField(
                        choices=[("suspect", "Suspect"), ("confirme", "Confirmé")],
                        max_length=20,
                        verbose_name="Type du cas",
                    ),
                ),
                (
                    "date_confirmation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de confirmation"
                    ),
                ),
                (
                    "date_declaration",
                    models.DateField(verbose_name="Date de déclaration"),
                ),
                (
                    "hospitalise",
                    models.BooleanField(default=False, verbose_name="Hospitalisé"),
                ),
                (
                    "date_hospitalisation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'hospitalisation"
                    ),
                ),
                ("decede", models.BooleanField(default=False, verbose_name="Décédé")),
                (
                    "date_deces",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du décès"
                    ),
                ),
                (
                    "formulaire_maladie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cas",
                        to="surveillance.formulairemaladie",
                        verbose_name="Maladie déclarée",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveillanceSentinelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proportion_ili",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Proportion ILI (%)",
                    ),
                ),
                (
                    "nombre_sari",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Nombre de cas SARI hospitalisés",
                    ),
                ),
                (
                    "proportion_diarrhees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Proportion de diarrhées aiguës (%)",
                    ),
                ),
                (
                    "proportion_conjonctivites",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Proportion de conjonctivites aiguës (%)",
                    ),
                ),
                (
                    "formulaire",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveillance_sentinelle",
                        to="surveillance.formulaire",
                        verbose_name="Formulaire",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="formulaire",
            constraint=models.UniqueConstraint(
                fields=("utilisateur", "annee_iso", "semaine_iso"),
                name="formulaire_unique_par_utilisateur_et_semaine",
            ),
        ),
        migrations.AddConstraint(
            model_name="evenement",
            constraint=models.UniqueConstraint(
                fields=("formulaire", "identifiant_evenement"),
                name="identifiant_evenement_unique_par_formulaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="formulairemaladie",
            constraint=models.UniqueConstraint(
                fields=("formulaire", "maladie"),
                name="maladie_unique_dans_un_formulaire",
            ),
        ),
    ]
